### ISSUE TITLE
multistore

### ISSUE THREAD

**Issue by tzs007** [karliuka/m2.Price#1]
Hi, how can I set rounded prices on a multistore website... Currently, I can set in global configuration, but it changes the price on both websites.

**Comment by karliuka** [comment]
Hi, thank you for your question. I had an [error](https://github.com/karliuka/m2.Price/commit/0b46fb7ef264a30face53130786f0544082c62d6) in the configuration file. Now you can to disable extension in global configuration and to enable (change settings) to the target website (store view).
