### ISSUE TITLE
Discount by code amount is not showing in order details

### ISSUE THREAD

**Issue by khadkamhn** [karliuka/m2.Price#10]
After enable this plugin I have fetched an issue.
In order history or admin of orders page, there is not showing any discount amount that is discounted by coupon/code.

**Comment by karliuka** [comment]
discount amount on admin order page:
![price](https://user-images.githubusercontent.com/1991955/37987380-bb411be8-3206-11e8-8645-495daaa94c83.png)

or i'm not looking there?

**Comment by khadkamhn** [comment]
@karliuka 
I mean in both customer order history and admin panel. Also html string is not supported in order list in admin page.
Its not working in my magento 2.2.1 because discount amount return negative value.
therefore I just changed some code to fix it.
`if($price<0){`
			`$amt = abs($price);`
			`return '('.str_replace('-','',$proceed($amt,$options)).')';`
		`}`
		`return $this->_helper->getZeroPriceText();`
https://github.com/karliuka/m2.Price/blob/24246d001701716556114a2bd3e1b0827a0e31b2/Plugin/Directory/Model/Currency.php#L138
