### ISSUE TITLE
Not working with Incl Tax

### ISSUE THREAD

**Issue by jaiminmagedelight** [karliuka/m2.Price#16]
Hello,

I have enabled Incl and Excl tax price on Product list and detail page. When I enabled this module then its only rounding Excl price, not Incl and old price.

**Comment by progcode** [comment]
I have this issue too

**Comment by TectonicKestrel** [comment]
It would be great if this could be sorted, my products are all added exc VAT and i list products inc and exc VAT, but i would like the inc VAT prices to be the price that is rounded, not the exc.

**Comment by karliuka** [comment]
Sorry, but we have no permissions to delegate the functions of the fiscal department to self ... rounding of prices including tax is not possible.
