### ISSUE TITLE
Weird behavior 

### ISSUE THREAD

**Issue by xnhinzkyx** [karliuka/m2.Price#2]
For some products it's working fine but on the other it's not, like 149.5 will show 150 which is correct and the other products will still shows the 2 decimal point.

I did reindex and clear/flush the cache many times but still the issue persists. Any fix for this?

Magento 2.1.4

**Comment by karliuka** [comment]
The text format (decimal points control, zero price as text) of price derivation is already in process.

**Comment by karliuka** [comment]
I updated the release.

**Comment by xnhinzkyx** [comment]
Thanks!

I'll update it and will let you know if it's fixed or not.

**Comment by xnhinzkyx** [comment]
Still the same. Please see screenshots

![akustisk flygel piano flygel keyboard instrumenter](https://cloud.githubusercontent.com/assets/2484559/24585960/5bc01a8c-17c9-11e7-9e42-ebea982dcf70.png)
![configuration settings stores magento admin](https://cloud.githubusercontent.com/assets/2484559/24585959/5bbd9730-17c9-11e7-8dcc-af9ad1c8fd28.png)

**Comment by karliuka** [comment]
Something is wrong in your installation. On the configuration screen, two lines 'Show decimal zeros'.
Front screen must be on luma theme. In custom themes I often find similar code http://prntscr.com/es8k3t

**Comment by xnhinzkyx** [comment]
Sorry my bad, I mess up with the screenshot tool. I only have one "Show decimal zeros" and I am using Porto theme.

**Comment by xnhinzkyx** [comment]
Is there any update or fix for this?

**Comment by karliuka** [comment]
Sorry, to fix the bugs of the Porto theme, please contact the author of the Porto theme.
