### ISSUE TITLE
Store rounding prices - UP

### ISSUE THREAD

**Issue by wajahatbashir** [karliuka/m2.Price#20]
Hi,

I want minor change in this extension.

My Price are coming on store like as

Now: $59.40, $124.1, $128.56, $70.87

Required: $60, $125, $129, $71

How to i can set prices in setting for required result like this. because I want to round up.

if 30.02 is coming then round price should be 31 not 30.

If there is any custom change, please guide me which code I'll change for this result ?

Thank You.

**Comment by karliuka** [comment]
Thank You
The new release of the module contains two new rounding processors (Simple Round up and Simple Round down). The first will completely solve this problem.
Please update the module.
