### ISSUE TITLE
Swedish rounding

### ISSUE THREAD

**Issue by ScIT-Raphael** [karliuka/m2.Price#3]
Hi

Thanks for the useful extension! Just have done some first checks in our demo envroiment and have noticed that you not can "Swedish Round" (round to the next 0.05, for example: 2.42 => 2.40 / 2.43 => 2.45).

Is it possible, that you can implement this feature?

Normaly it works over this small code snip:
`$betrag = round(($betrag + 0.000001) * 20) / 20;`

Best Regards
Raphael

**Comment by karliuka** [comment]
Hi
Thanks, this is an interesting idea. I will try to implement it.

**Comment by karliuka** [comment]
Update the module, please

**Comment by ScIT-Raphael** [comment]
Thanks for the modification, it works really well! Is there any possibillity to do this also in the shopping cart? 
![image](https://user-images.githubusercontent.com/13765400/27073281-9786899c-5023-11e7-99c4-4aa8479db0b2.png)

So it should round also the "order total".

**Comment by karliuka** [comment]
Its interesting bug ...

**Comment by ScIT-Raphael** [comment]
Do you think you can fix this "bug"?

**Comment by karliuka** [comment]
Fixed. Check, please.

**Comment by ScIT-Raphael** [comment]
Guy, you rock! Thanks for fix, works well. Will close this issue/request now - but if you want, pleace create a donation button - would like to spend you something for your work!

**Comment by ScIT-Raphael** [comment]
I just allow myself to reopen the thread. I've noted that there is a problem with the calculation, as soon, as you use "display price including taxes". For example: Customer use a product price excl. vat (8%) from 310.19. Now magento 2 shows the customer 335.01 (including tax). Your module rounds the price (310.19 to 310.20, so magento 2 shows the customer 335.02 instead of rounding to 335.00). Can you maybe find a fix for this problem? Thanks for your great work!

**Comment by karliuka** [comment]
Ok, i will try.

**Comment by maderlock** [comment]
Just so you know, I didn't recognise the term "Swedish Rounding". I think that most of the world knows this as "Cash Rounding"
