### ISSUE TITLE
Magento 2.1.5, wrong price in configurable product

### ISSUE THREAD

**Issue by magewallet** [karliuka/m2.Price#4]
Hello

Thanks for making good extensions that helps every website.

I am facing one issue as below.
For configurable product wrong price displayed.

I have 3 stores. There are 2 different currency for different stores.
Store 1 > Basic currency > EURO.
Store 2 > EURO.
Store 3 > Kč

Once I am on 3rd store (Kč currency).

E.g:
For Product 1
Base price: 2.50 Euro
Kč Price:  65.10 (rate like 1 euro = 26.0410 Kc)

After Round price it shows = (2.50 * 26.0410) = 65 Kč > This is perfect for simple product and on list page.

But it is showing wrong price on product details page and configurable product.
It shows

(2.50 * 26.0410 * 26.0410) = 1 693,00 Kč something. Which is not good. It should only display 65 Kc.

For more information please see attached screenshot.

![home-page-product-price](https://user-images.githubusercontent.com/14808082/28665893-d1a0d556-72e2-11e7-9674-85d5f695cd19.png)
![product-detail-page-good-price-select-swatch](https://user-images.githubusercontent.com/14808082/28665912-e68291b2-72e2-11e7-8ac2-0347cacf08a7.png)
![Uploading product-detail-page-price-2times.png…]()

**Comment by magewallet** [comment]
Please find this screenshot


![product-detail-page-good-price-select-swatch](https://user-images.githubusercontent.com/14808082/28665944-00d12376-72e3-11e7-9a4b-f513e83e8162.png)

**Comment by karliuka** [comment]
Hi.
On which screen can i see the price of 1 693,00 Kč?
This is the first. Second, please create an additional display case with the default theme(Luma) and make screenshots from it. There is an assumption that this is a bug of your custom theme.
