### ISSUE TITLE
Only rounds display price

### ISSUE THREAD

**Issue by maderlock** [karliuka/m2.Price#5]
Setup
1. Product with base price of $10
2. Current conversion to GBP is e.g. £7.89

Action
1. Display as GBP - rounds to £8
2. Go through checkout and pay for item

Expected
1. Displayed £8 is what the customer expects to pay. The conversion of £8 to USD might be $10.14. This is what should be paid as it is the base currency version of what has been displayed

Actual
1. The customer is charged exactly $10

What seems to have happened is that the rounding is only for display. We cannot do this as it would be false advertising to display one price but then use another for actually charging.

What I would have hoped to see is this conversion back to the base currency. Do you think this is possible?

**Comment by karliuka** [comment]
Really magento does not use reverse conversion. Instead, the magento conducts two calculation processes, the first for the base currency, the second for the store currency.
Look at the quote_item, quote and etc tables and you will see pairs of fields subtotal and base_subtotal, price and base_price, discount_amount and base_discount_amount ...
Depending on the situation, the system uses the necessary(base or store) price.
Changing this logic requires a strong intervention in the core of the system. It's easier to just delete the string 'Your credit card will be charged for $10' (so as not to mislead the buyer), transfer total in the store currency(£8) to the payment gateway and delegate gateway the final conversion process (here you can see the amount of $10.14).

**Comment by maderlock** [comment]
A good workaround in the general case.

Sadly the reason I'm using this module is because the payment gateway does not support payment in the viewed currency (in this case AED - very few support it directly).
