### ISSUE TITLE
Configurable Products Rounding

### ISSUE THREAD

**Issue by stefas1** [karliuka/m2.Price#7]
Hello,
We see that rounding doesn't work on configurable products. Do you have any suggestions ?

**Comment by karliuka** [comment]
I do not see a problem with rounding the prices of configurable products.
Configurable products rounding off
![round-off](https://user-images.githubusercontent.com/1991955/32839611-a5f69e62-ca1d-11e7-923f-2a039000043d.png)
Configurable products rounding on
![round-on](https://user-images.githubusercontent.com/1991955/32839612-a615201c-ca1d-11e7-90ca-56f16ee3beb3.png)

**Comment by stefas1** [comment]
Hi @karliuka,
Thanks for the quick reply. Have you tried to check functionality with configurable products using different prices for childs ?
I was referring to that inability.
To clarify, it seems that when you have configurable products with different prices on simples, then the price is not correct. But if you add the product to cart then the rounding works fine there.

Kind Regards

**Comment by karliuka** [comment]
I do not see a problem with rounding the prices of configurable products, using different prices for childs.
first child:
![1](https://user-images.githubusercontent.com/1991955/32878389-7953d852-caae-11e7-8b82-0aefb869e062.png)
![3](https://user-images.githubusercontent.com/1991955/32878390-797d1dc0-caae-11e7-83a9-cc0f586b8afa.png)
second child:
![2](https://user-images.githubusercontent.com/1991955/32878417-979a00c0-caae-11e7-8797-3ead202f0cd8.png)
![4](https://user-images.githubusercontent.com/1991955/32878418-97c22294-caae-11e7-915e-304ad594da65.png)
