### ISSUE TITLE
When using "Catalog Price Rule" Discount Percentage, the total is not rounded

### ISSUE THREAD

**Issue by diego-mathis** [karliuka/m2.Price#8]
I have following configuration:
> Enabled Rounding: yes
> Rounding Base Price: no
> Rounding Type: Swedish Round
> Swedish Fraction: 0.05
> Substract Amount: Yes
> Amount: 0.01
> Show decimal zeros: Yes
> Replace zero price: No

When using a discount percentage, it subtracts the discount correctly, but then it does not round it.

![discount_percentage](https://user-images.githubusercontent.com/22345162/34200079-16753faa-e570-11e7-92dc-bf45ebdd11ba.PNG)

**Comment by karliuka** [comment]
ok ... I need some time

**Comment by karliuka** [comment]
update the module, please
set config 'Rounding Discount' to Yes

**Comment by diego-mathis** [comment]
It works perfectly - thanks you!
